from sqlalchemy import Column, Integer, BigInteger, String, Boolean, Text, Date, DateTime, Numeric, ForeignKey
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.database import Base
from app.models.core_models import (
    TenantMaster, EntityMaster, Department, Office, FinancialYear,
    BudgetHead, CodeMaster, BranchMaster, BmScheme, BmProject, BudgetSnapshot
)

class MtrlItemCat(Base):
    __tablename__ = "mtrl_item_cat"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    cat_code = Column(String(50), nullable=False, unique=True)
    cat_name = Column(String(150), nullable=False)
    parent_cat_id = Column(BigInteger, ForeignKey("mtrl_item_cat.id"))
    hsn_sac_code = Column(String(20))
    is_capital = Column(Boolean, default=False)
    is_active = Column(Boolean, default=True)
    created_by = Column(BigInteger)
    created_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())
    updated_by = Column(BigInteger)
    updated_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())
    
    items = relationship("MtrlItem", back_populates="category")

class MtrlUom(Base):
    __tablename__ = "mtrl_uom"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    uom_code = Column(String(20), nullable=False, unique=True)
    uom_name = Column(String(100), nullable=False)
    uom_type = Column(String(50))
    precision_digits = Column(Integer, default=0)
    is_active = Column(Boolean, default=True)
    created_by = Column(BigInteger)
    created_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())
    updated_by = Column(BigInteger)
    updated_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())

class MtrlUomConv(Base):
    __tablename__ = "mtrl_uom_conv"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    from_uom_id = Column(BigInteger, ForeignKey("mtrl_uom.id"), nullable=False)
    to_uom_id = Column(BigInteger, ForeignKey("mtrl_uom.id"), nullable=False)
    conversion_factor = Column(Numeric(14, 6), nullable=False)
    is_active = Column(Boolean, default=True)
    created_by = Column(BigInteger)
    created_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())

class MtrlItem(Base):
    __tablename__ = "mtrl_item"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    financial_year_id = Column(Integer, ForeignKey("financial_years.id"))
    item_code = Column(String(50), nullable=False, unique=True)
    item_name = Column(String(255), nullable=False)
    item_desc = Column(Text)
    cat_id = Column(BigInteger, ForeignKey("mtrl_item_cat.id"), nullable=False)
    base_uom_id = Column(BigInteger, ForeignKey("mtrl_uom.id"), nullable=False)
    alt_uom_id = Column(BigInteger, ForeignKey("mtrl_uom.id"))
    uom_conv_factor = Column(Numeric(14, 4), default=1.0)
    item_type = Column(String(50), default='GOODS')
    is_service = Column(Boolean, default=False)
    is_stockable = Column(Boolean, default=True)
    is_returnable_tool = Column(Boolean, default=False)
    is_capital = Column(Boolean, default=False)
    is_consumable = Column(Boolean, default=True)
    hsn_sac_code = Column(String(20))
    gst_rate_pct = Column(Numeric(5, 2), default=18.0)
    budget_head_id = Column(Integer, ForeignKey("budget_heads.id"))
    brand_name = Column(String(150))
    make_model = Column(String(150))
    material_grade = Column(String(150))
    tolerance_pct = Column(Numeric(5, 2), default=0.0)
    image_url = Column(Text)
    min_stock_level = Column(Numeric(14, 2), default=0)
    max_stock_level = Column(Numeric(14, 2), default=0)
    reorder_level = Column(Numeric(14, 2), default=0)
    reorder_qty = Column(Numeric(14, 2), default=0)
    lead_time_days = Column(Integer, default=7)
    estimated_rate = Column(Numeric(18, 2), default=0)
    shelf_life_days = Column(Integer)
    is_active = Column(Boolean, default=True)
    created_by = Column(BigInteger)
    created_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())
    updated_by = Column(BigInteger)
    updated_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())

    category = relationship("MtrlItemCat", back_populates="items")
    base_uom = relationship("MtrlUom", foreign_keys=[base_uom_id])
    alt_uom = relationship("MtrlUom", foreign_keys=[alt_uom_id])
    variants = relationship("MtrlVariant", back_populates="item", cascade="all, delete-orphan")

class MtrlVariant(Base):
    __tablename__ = "mtrl_variant"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    item_id = Column(BigInteger, ForeignKey("mtrl_item.id", ondelete="CASCADE"), nullable=False)
    variant_code = Column(String(60), nullable=False, unique=True)
    variant_name = Column(String(255), nullable=False)
    size_spec = Column(String(100))
    color_finish = Column(String(100))
    brand_make = Column(String(150))
    material_variety = Column(String(150))
    tolerance_spec = Column(String(100))
    barcode_sku = Column(String(100))
    image_url = Column(Text)
    variant_rate = Column(Numeric(18, 2), default=0)
    is_active = Column(Boolean, default=True)
    created_by = Column(BigInteger)
    created_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())
    updated_by = Column(BigInteger)
    updated_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())

    item = relationship("MtrlItem", back_populates="variants")

class MtrlBoq(Base):
    __tablename__ = "mtrl_boq"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    boq_item_code = Column(String(50), nullable=False)
    boq_desc = Column(Text, nullable=False)
    sor_code = Column(String(50))
    item_id = Column(BigInteger, ForeignKey("mtrl_item.id"), nullable=False)
    variant_id = Column(BigInteger, ForeignKey("mtrl_variant.id"))
    tender_uom_id = Column(BigInteger, ForeignKey("mtrl_uom.id"), nullable=False)
    inv_uom_id = Column(BigInteger, ForeignKey("mtrl_uom.id"), nullable=False)
    conversion_factor = Column(Numeric(14, 4), default=1.0)
    is_active = Column(Boolean, default=True)
    created_by = Column(BigInteger)
    created_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())

    item = relationship("MtrlItem")

class MtrlParty(Base):
    __tablename__ = "mtrl_party"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    party_code = Column(String(50), nullable=False, unique=True)
    party_name = Column(String(255), nullable=False)
    trade_name = Column(String(255))
    party_type = Column(String(50), default='VENDOR')
    gstin = Column(String(15), nullable=False)
    pan_no = Column(String(10), nullable=False)
    gem_seller_id = Column(String(50))
    msme_reg_no = Column(String(50))
    bank_account_no = Column(String(50))
    bank_ifsc = Column(String(20))
    credit_period_days = Column(Integer, default=30)
    party_rating = Column(Numeric(3, 2), default=5.0)
    is_blacklisted = Column(Boolean, default=False)
    is_active = Column(Boolean, default=True)
    created_by = Column(BigInteger)
    created_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())
    updated_by = Column(BigInteger)
    updated_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())

    addresses = relationship("MtrlPartyAd", back_populates="party", cascade="all, delete-orphan")
    contacts = relationship("MtrlPartyCn", back_populates="party", cascade="all, delete-orphan")

class MtrlPartyAd(Base):
    __tablename__ = "mtrl_party_ad"
    id = Column(BigInteger, primary_key=True, index=True)
    party_id = Column(BigInteger, ForeignKey("mtrl_party.id", ondelete="CASCADE"), nullable=False)
    address_type = Column(String(50), nullable=False)
    address_line = Column(Text, nullable=False)
    city = Column(String(100), nullable=False)
    district = Column(String(100))
    state_code = Column(String(10), nullable=False)
    pincode = Column(String(10), nullable=False)
    is_primary = Column(Boolean, default=False)

    party = relationship("MtrlParty", back_populates="addresses")

class MtrlPartyCn(Base):
    __tablename__ = "mtrl_party_cn"
    id = Column(BigInteger, primary_key=True, index=True)
    party_id = Column(BigInteger, ForeignKey("mtrl_party.id", ondelete="CASCADE"), nullable=False)
    contact_person = Column(String(150), nullable=False)
    designation = Column(String(100))
    phone = Column(String(20), nullable=False)
    mobile = Column(String(20))
    email = Column(String(150))
    department = Column(String(100))
    is_primary = Column(Boolean, default=False)

    party = relationship("MtrlParty", back_populates="contacts")

class MtrlStore(Base):
    __tablename__ = "mtrl_store"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    store_code = Column(String(50), nullable=False, unique=True)
    store_name = Column(String(150), nullable=False)
    store_type = Column(String(50), default='CENTRAL')
    incharge_user_id = Column(BigInteger)
    location_address = Column(Text)
    is_active = Column(Boolean, default=True)
    created_by = Column(BigInteger)
    created_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())

class MtrlReq(Base):
    __tablename__ = "mtrl_req"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    financial_year_id = Column(Integer, ForeignKey("financial_years.id"), nullable=False)
    req_no = Column(String(50), nullable=False, unique=True)
    req_date = Column(Date, default=func.current_date())
    target_store_id = Column(BigInteger, ForeignKey("mtrl_store.id"), nullable=False)
    budget_head_id = Column(Integer, ForeignKey("budget_heads.id"))
    scheme_id = Column(Integer, ForeignKey("bm_scheme.id"))
    project_id = Column(Integer, ForeignKey("bm_project.id"))
    total_est_amount = Column(Numeric(18, 2), default=0)
    committed_amount = Column(Numeric(18, 2), default=0)
    budget_snapshot_id = Column(BigInteger, ForeignKey("tb_budget_balance_snapshots.id"))
    priority = Column(String(20), default='Normal')
    purpose = Column(Text)
    req_status_id = Column(BigInteger, ForeignKey("code_master.code_mst_id"))
    current_stage = Column(String(100), default='Submitted')
    assigned_to = Column(BigInteger)
    approved_by = Column(BigInteger)
    approved_at = Column(DateTime(timezone=True))
    rejection_remarks = Column(Text)
    created_by = Column(BigInteger)
    created_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())
    updated_by = Column(BigInteger)
    updated_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())

    store = relationship("MtrlStore")
    lines = relationship("MtrlReqLine", back_populates="requisition", cascade="all, delete-orphan")

class MtrlReqLine(Base):
    __tablename__ = "mtrl_req_line"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    req_id = Column(BigInteger, ForeignKey("mtrl_req.id", ondelete="CASCADE"), nullable=False)
    item_id = Column(BigInteger, ForeignKey("mtrl_item.id"), nullable=False)
    variant_id = Column(BigInteger, ForeignKey("mtrl_variant.id"))
    requested_qty = Column(Numeric(14, 2), nullable=False)
    approved_qty = Column(Numeric(14, 2), default=0)
    uom_id = Column(BigInteger, ForeignKey("mtrl_uom.id"), nullable=False)
    est_unit_rate = Column(Numeric(18, 2), nullable=False)
    line_est_amount = Column(Numeric(18, 2), nullable=False)
    required_by_date = Column(Date)
    technical_spec = Column(Text)
    preferred_make = Column(String(150))
    procured_qty = Column(Numeric(14, 2), default=0)
    issued_qty = Column(Numeric(14, 2), default=0)
    line_status_id = Column(BigInteger, ForeignKey("code_master.code_mst_id"))

    requisition = relationship("MtrlReq", back_populates="lines")
    item = relationship("MtrlItem")
    variant = relationship("MtrlVariant")
    uom = relationship("MtrlUom")

class MtrlProcPln(Base):
    __tablename__ = "mtrl_proc_pln"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    financial_year_id = Column(Integer, ForeignKey("financial_years.id"), nullable=False)
    plan_no = Column(String(50), nullable=False, unique=True)
    total_budget = Column(Numeric(18, 2), default=0)
    planned_value = Column(Numeric(18, 2), default=0)
    proc_mode = Column(String(50), default='GeM')
    status_id = Column(BigInteger, ForeignKey("code_master.code_mst_id"))
    created_by = Column(BigInteger)
    created_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())

class MtrlTender(Base):
    __tablename__ = "mtrl_tender"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    financial_year_id = Column(Integer, ForeignKey("financial_years.id"), nullable=False)
    tender_no = Column(String(100), nullable=False, unique=True)
    tender_title = Column(String(255), nullable=False)
    tender_date = Column(Date, nullable=False)
    proc_mode = Column(String(50), default='Open Tender')
    portal_ref_no = Column(String(100))
    budget_head_id = Column(Integer, ForeignKey("budget_heads.id"))
    estimated_cost = Column(Numeric(18, 2), nullable=False)
    tender_fee = Column(Numeric(14, 2), default=0)
    emd_amount = Column(Numeric(18, 2), default=0)
    bid_start_date = Column(DateTime(timezone=True), nullable=False)
    bid_close_date = Column(DateTime(timezone=True), nullable=False)
    tech_open_date = Column(DateTime(timezone=True))
    fin_open_date = Column(DateTime(timezone=True))
    status_id = Column(BigInteger, ForeignKey("code_master.code_mst_id"))
    awarded_party_id = Column(BigInteger, ForeignKey("mtrl_party.id"))
    created_by = Column(BigInteger)
    created_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())

    awarded_party = relationship("MtrlParty")
    quotes = relationship("MtrlQuote", back_populates="tender", cascade="all, delete-orphan")

class MtrlQuote(Base):
    __tablename__ = "mtrl_quote"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    tender_id = Column(BigInteger, ForeignKey("mtrl_tender.id", ondelete="CASCADE"), nullable=False)
    party_id = Column(BigInteger, ForeignKey("mtrl_party.id"), nullable=False)
    item_id = Column(BigInteger, ForeignKey("mtrl_item.id"), nullable=False)
    variant_id = Column(BigInteger, ForeignKey("mtrl_variant.id"))
    quoted_qty = Column(Numeric(14, 2), nullable=False)
    basic_rate = Column(Numeric(18, 2), nullable=False)
    gst_percent = Column(Numeric(5, 2), default=18.0)
    gst_amount = Column(Numeric(18, 2), default=0)
    freight_charges = Column(Numeric(18, 2), default=0)
    total_unit_cost = Column(Numeric(18, 2), nullable=False)
    total_bid_value = Column(Numeric(18, 2), nullable=False)
    rank_order = Column(Integer)
    is_technically_ok = Column(Boolean, default=True)
    eval_remarks = Column(Text)
    is_selected = Column(Boolean, default=False)
    created_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())

    tender = relationship("MtrlTender", back_populates="quotes")
    party = relationship("MtrlParty")
    item = relationship("MtrlItem")

class MtrlWo(Base):
    __tablename__ = "mtrl_wo"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    financial_year_id = Column(Integer, ForeignKey("financial_years.id"), nullable=False)
    wo_no = Column(String(60), nullable=False, unique=True)
    wo_date = Column(Date, default=func.current_date())
    tender_id = Column(BigInteger, ForeignKey("mtrl_tender.id"))
    req_id = Column(BigInteger, ForeignKey("mtrl_req.id"))
    party_id = Column(BigInteger, ForeignKey("mtrl_party.id"), nullable=False)
    budget_head_id = Column(Integer, ForeignKey("budget_heads.id"))
    total_basic_amt = Column(Numeric(18, 2), nullable=False)
    total_tax_amt = Column(Numeric(18, 2), nullable=False)
    total_wo_amount = Column(Numeric(18, 2), nullable=False)
    pb_guarantee_amt = Column(Numeric(18, 2), default=0)
    delivery_due_date = Column(Date, nullable=False)
    delivery_store_id = Column(BigInteger, ForeignKey("mtrl_store.id"), nullable=False)
    payment_terms = Column(Text)
    ld_clause_terms = Column(Text)
    status_id = Column(BigInteger, ForeignKey("code_master.code_mst_id"))
    approved_by = Column(BigInteger)
    created_by = Column(BigInteger)
    created_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())
    updated_by = Column(BigInteger)
    updated_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())

    party = relationship("MtrlParty")
    delivery_store = relationship("MtrlStore")
    lines = relationship("MtrlWoLine", back_populates="work_order", cascade="all, delete-orphan")
    amendments = relationship("MtrlWoAmend", back_populates="work_order", cascade="all, delete-orphan")

class MtrlWoLine(Base):
    __tablename__ = "mtrl_wo_line"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    wo_id = Column(BigInteger, ForeignKey("mtrl_wo.id", ondelete="CASCADE"), nullable=False)
    item_id = Column(BigInteger, ForeignKey("mtrl_item.id"), nullable=False)
    variant_id = Column(BigInteger, ForeignKey("mtrl_variant.id"))
    order_qty = Column(Numeric(14, 2), nullable=False)
    uom_id = Column(BigInteger, ForeignKey("mtrl_uom.id"), nullable=False)
    unit_rate = Column(Numeric(18, 2), nullable=False)
    tax_percent = Column(Numeric(5, 2), default=18.0)
    tax_amount = Column(Numeric(18, 2), nullable=False)
    total_line_amount = Column(Numeric(18, 2), nullable=False)
    delivered_qty = Column(Numeric(14, 2), default=0)
    accepted_qty = Column(Numeric(14, 2), default=0)
    rejected_qty = Column(Numeric(14, 2), default=0)
    line_status_id = Column(BigInteger, ForeignKey("code_master.code_mst_id"))

    work_order = relationship("MtrlWo", back_populates="lines")
    item = relationship("MtrlItem")
    variant = relationship("MtrlVariant")
    uom = relationship("MtrlUom")

class MtrlWoAmend(Base):
    __tablename__ = "mtrl_wo_amend"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    amend_no = Column(String(60), nullable=False, unique=True)
    wo_id = Column(BigInteger, ForeignKey("mtrl_wo.id"), nullable=False)
    amend_date = Column(Date, default=func.current_date())
    amend_type = Column(String(50), nullable=False)
    old_value = Column(Numeric(18, 2))
    new_value = Column(Numeric(18, 2))
    reason = Column(Text, nullable=False)
    approval_ref_no = Column(String(100))
    approved_by = Column(BigInteger)
    status_id = Column(BigInteger, ForeignKey("code_master.code_mst_id"))
    created_by = Column(BigInteger)
    created_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())

    work_order = relationship("MtrlWo", back_populates="amendments")

class MtrlDelivery(Base):
    __tablename__ = "mtrl_delivery"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    delivery_ref_no = Column(String(100), nullable=False)
    wo_id = Column(BigInteger, ForeignKey("mtrl_wo.id"), nullable=False)
    party_id = Column(BigInteger, ForeignKey("mtrl_party.id"), nullable=False)
    dispatch_date = Column(Date, nullable=False)
    expected_date = Column(Date, nullable=False)
    courier_transporter = Column(String(150))
    lr_docket_no = Column(String(100))
    vehicle_no = Column(String(50))
    e_way_bill_no = Column(String(50))
    delivery_status = Column(String(50), default='In Transit')
    received_date = Column(Date)
    created_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())

    work_order = relationship("MtrlWo")
    party = relationship("MtrlParty")

class MtrlGrn(Base):
    __tablename__ = "mtrl_grn"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    financial_year_id = Column(Integer, ForeignKey("financial_years.id"))
    grn_no = Column(String(60), nullable=False, unique=True)
    grn_date = Column(Date, default=func.current_date())
    wo_id = Column(BigInteger, ForeignKey("mtrl_wo.id"), nullable=False)
    party_id = Column(BigInteger, ForeignKey("mtrl_party.id"), nullable=False)
    store_id = Column(BigInteger, ForeignKey("mtrl_store.id"), nullable=False)
    challan_no = Column(String(100), nullable=False)
    challan_date = Column(Date, nullable=False)
    gate_entry_no = Column(String(60))
    gate_entry_date = Column(DateTime(timezone=True))
    vehicle_number = Column(String(50))
    driver_name = Column(String(100))
    receiver_user_id = Column(BigInteger, nullable=False)
    inspection_status = Column(String(50), default='Pending')
    posting_status = Column(String(50), default='Draft')
    remarks = Column(Text)
    created_by = Column(BigInteger)
    created_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())
    updated_by = Column(BigInteger)
    updated_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())

    work_order = relationship("MtrlWo")
    party = relationship("MtrlParty")
    store = relationship("MtrlStore")
    lines = relationship("MtrlGrnLine", back_populates="grn", cascade="all, delete-orphan")
    inspections = relationship("MtrlInsp", back_populates="grn", cascade="all, delete-orphan")

class MtrlGrnLine(Base):
    __tablename__ = "mtrl_grn_line"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    grn_id = Column(BigInteger, ForeignKey("mtrl_grn.id", ondelete="CASCADE"), nullable=False)
    wo_line_id = Column(BigInteger, ForeignKey("mtrl_wo_line.id"), nullable=False)
    item_id = Column(BigInteger, ForeignKey("mtrl_item.id"), nullable=False)
    variant_id = Column(BigInteger, ForeignKey("mtrl_variant.id"))
    challan_qty = Column(Numeric(14, 2), nullable=False)
    received_qty = Column(Numeric(14, 2), nullable=False)
    accepted_qty = Column(Numeric(14, 2), default=0)
    rejected_qty = Column(Numeric(14, 2), default=0)
    damaged_qty = Column(Numeric(14, 2), default=0)
    shortage_qty = Column(Numeric(14, 2), default=0)
    excess_qty = Column(Numeric(14, 2), default=0)
    batch_number = Column(String(60))
    mfg_date = Column(Date)
    expiry_date = Column(Date)
    storage_bin = Column(String(50))
    line_status = Column(String(50), default='Received')

    grn = relationship("MtrlGrn", back_populates="lines")
    item = relationship("MtrlItem")
    variant = relationship("MtrlVariant")

class MtrlInsp(Base):
    __tablename__ = "mtrl_insp"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    insp_no = Column(String(60), nullable=False, unique=True)
    grn_id = Column(BigInteger, ForeignKey("mtrl_grn.id"), nullable=False)
    insp_date = Column(Date, default=func.current_date())
    inspector_id = Column(BigInteger, nullable=False)
    test_type = Column(String(50), default='Physical & Dimensional Check')
    sample_size = Column(Numeric(14, 2))
    passed_qty = Column(Numeric(14, 2), nullable=False)
    rejected_qty = Column(Numeric(14, 2), default=0)
    rejection_reason = Column(Text)
    test_certificate_no = Column(String(100))
    overall_status = Column(String(50), default='Approved')
    created_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())

    grn = relationship("MtrlGrn", back_populates="inspections")

class MtrlRtv(Base):
    __tablename__ = "mtrl_rtv"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    rtv_no = Column(String(60), nullable=False, unique=True)
    grn_id = Column(BigInteger, ForeignKey("mtrl_grn.id"), nullable=False)
    party_id = Column(BigInteger, ForeignKey("mtrl_party.id"), nullable=False)
    item_id = Column(BigInteger, ForeignKey("mtrl_item.id"), nullable=False)
    variant_id = Column(BigInteger, ForeignKey("mtrl_variant.id"))
    return_qty = Column(Numeric(14, 2), nullable=False)
    return_reason = Column(Text, nullable=False)
    rtv_date = Column(Date, default=func.current_date())
    gatepass_no = Column(String(60))
    status_id = Column(BigInteger, ForeignKey("code_master.code_mst_id"))
    created_by = Column(BigInteger)
    created_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())

    party = relationship("MtrlParty")
    item = relationship("MtrlItem")
    grn = relationship("MtrlGrn")

class MtrlStock(Base):
    __tablename__ = "mtrl_stock"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    store_id = Column(BigInteger, ForeignKey("mtrl_store.id"), nullable=False)
    item_id = Column(BigInteger, ForeignKey("mtrl_item.id"), nullable=False)
    variant_id = Column(BigInteger, ForeignKey("mtrl_variant.id"))
    batch_no = Column(String(60), default='DEFAULT')
    available_qty = Column(Numeric(14, 2), default=0)
    allocated_qty = Column(Numeric(14, 2), default=0)
    quarantine_qty = Column(Numeric(14, 2), default=0)
    damaged_qty = Column(Numeric(14, 2), default=0)
    avg_unit_cost = Column(Numeric(18, 2), default=0)
    total_stock_value = Column(Numeric(18, 2), default=0)
    storage_bin = Column(String(50))
    last_issued_date = Column(Date)
    last_received_date = Column(Date)
    updated_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())

    store = relationship("MtrlStore")
    item = relationship("MtrlItem")
    variant = relationship("MtrlVariant")

class MtrlMovement(Base):
    __tablename__ = "mtrl_movement"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    financial_year_id = Column(Integer, ForeignKey("financial_years.id"))
    store_id = Column(BigInteger, ForeignKey("mtrl_store.id"), nullable=False)
    item_id = Column(BigInteger, ForeignKey("mtrl_item.id"), nullable=False)
    variant_id = Column(BigInteger, ForeignKey("mtrl_variant.id"))
    txn_type = Column(String(50), nullable=False)
    ref_doc_type = Column(String(50), nullable=False)
    ref_doc_id = Column(BigInteger, nullable=False)
    ref_doc_no = Column(String(60), nullable=False)
    opening_qty = Column(Numeric(14, 2), nullable=False)
    txn_qty = Column(Numeric(14, 2), nullable=False)
    closing_qty = Column(Numeric(14, 2), nullable=False)
    unit_rate = Column(Numeric(18, 2), default=0)
    txn_amount = Column(Numeric(18, 2), default=0)
    txn_timestamp = Column(DateTime(timezone=True), server_default=func.clock_timestamp())
    performed_by = Column(BigInteger)
    remarks = Column(Text)

    store = relationship("MtrlStore")
    item = relationship("MtrlItem")

class MtrlTransfer(Base):
    __tablename__ = "mtrl_transfer"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    transfer_no = Column(String(60), nullable=False, unique=True)
    transfer_date = Column(Date, default=func.current_date())
    from_store_id = Column(BigInteger, ForeignKey("mtrl_store.id"), nullable=False)
    to_store_id = Column(BigInteger, ForeignKey("mtrl_store.id"), nullable=False)
    item_id = Column(BigInteger, ForeignKey("mtrl_item.id"), nullable=False)
    variant_id = Column(BigInteger, ForeignKey("mtrl_variant.id"))
    transfer_qty = Column(Numeric(14, 2), nullable=False)
    dispatch_gatepass = Column(String(60))
    received_qty = Column(Numeric(14, 2))
    status_id = Column(BigInteger, ForeignKey("code_master.code_mst_id"))
    dispatched_by = Column(BigInteger)
    received_by = Column(BigInteger)
    created_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())

    from_store = relationship("MtrlStore", foreign_keys=[from_store_id])
    to_store = relationship("MtrlStore", foreign_keys=[to_store_id])
    item = relationship("MtrlItem")

class MtrlIssue(Base):
    __tablename__ = "mtrl_issue"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    financial_year_id = Column(Integer, ForeignKey("financial_years.id"))
    issue_no = Column(String(60), nullable=False, unique=True)
    issue_date = Column(Date, default=func.current_date())
    req_id = Column(BigInteger, ForeignKey("mtrl_req.id"))
    store_id = Column(BigInteger, ForeignKey("mtrl_store.id"), nullable=False)
    receiver_name = Column(String(150), nullable=False)
    receiver_user_id = Column(BigInteger)
    scheme_id = Column(Integer, ForeignKey("bm_scheme.id"))
    project_id = Column(Integer, ForeignKey("bm_project.id"))
    total_issue_val = Column(Numeric(18, 2), default=0)
    status_id = Column(BigInteger, ForeignKey("code_master.code_mst_id"))
    issued_by = Column(BigInteger)
    created_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())

    store = relationship("MtrlStore")
    lines = relationship("MtrlIssLine", back_populates="issue", cascade="all, delete-orphan")

class MtrlIssLine(Base):
    __tablename__ = "mtrl_iss_line"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    issue_id = Column(BigInteger, ForeignKey("mtrl_issue.id", ondelete="CASCADE"), nullable=False)
    item_id = Column(BigInteger, ForeignKey("mtrl_item.id"), nullable=False)
    variant_id = Column(BigInteger, ForeignKey("mtrl_variant.id"))
    batch_no = Column(String(60))
    requested_qty = Column(Numeric(14, 2), nullable=False)
    issued_qty = Column(Numeric(14, 2), nullable=False)
    unit_rate = Column(Numeric(18, 2), nullable=False)
    total_cost = Column(Numeric(18, 2), nullable=False)
    asset_serial_no = Column(String(100))
    remarks = Column(Text)

    issue = relationship("MtrlIssue", back_populates="lines")
    item = relationship("MtrlItem")

class MtrlReturn(Base):
    __tablename__ = "mtrl_return"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    return_no = Column(String(60), nullable=False, unique=True)
    issue_id = Column(BigInteger, ForeignKey("mtrl_issue.id"))
    store_id = Column(BigInteger, ForeignKey("mtrl_store.id"), nullable=False)
    item_id = Column(BigInteger, ForeignKey("mtrl_item.id"), nullable=False)
    variant_id = Column(BigInteger, ForeignKey("mtrl_variant.id"))
    return_qty = Column(Numeric(14, 2), nullable=False)
    condition_status = Column(String(50), default='Good')
    returned_by = Column(BigInteger)
    received_by = Column(BigInteger)
    created_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())

    store = relationship("MtrlStore")
    item = relationship("MtrlItem")

class MtrlToolIss(Base):
    __tablename__ = "mtrl_tool_iss"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    voucher_no = Column(String(60), nullable=False, unique=True)
    issue_date = Column(Date, default=func.current_date())
    store_id = Column(BigInteger, ForeignKey("mtrl_store.id"), nullable=False)
    item_id = Column(BigInteger, ForeignKey("mtrl_item.id"), nullable=False)
    variant_id = Column(BigInteger, ForeignKey("mtrl_variant.id"))
    tool_serial_code = Column(String(100))
    issued_qty = Column(Numeric(14, 2), default=1)
    worker_labor_name = Column(String(150), nullable=False)
    worker_id_card = Column(String(50))
    shift_name = Column(String(50), default='Morning Shift')
    issued_time = Column(DateTime(timezone=True), server_default=func.clock_timestamp())
    issued_by = Column(BigInteger)
    expected_return = Column(Date, default=func.current_date())
    returned_qty = Column(Numeric(14, 2), default=0)
    returned_time = Column(DateTime(timezone=True))
    received_by = Column(BigInteger)
    tool_condition = Column(String(50), default='Working')
    fine_damage_amt = Column(Numeric(14, 2), default=0)
    status = Column(String(50), default='Issued')
    remarks = Column(Text)

    store = relationship("MtrlStore")
    item = relationship("MtrlItem")

class MtrlInvoice(Base):
    __tablename__ = "mtrl_invoice"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    financial_year_id = Column(Integer, ForeignKey("financial_years.id"), nullable=False)
    inv_no = Column(String(60), nullable=False, unique=True)
    vendor_inv_no = Column(String(100), nullable=False)
    vendor_inv_date = Column(Date, nullable=False)
    received_date = Column(Date, default=func.current_date())
    wo_id = Column(BigInteger, ForeignKey("mtrl_wo.id"), nullable=False)
    grn_id = Column(BigInteger, ForeignKey("mtrl_grn.id"), nullable=False)
    party_id = Column(BigInteger, ForeignKey("mtrl_party.id"), nullable=False)
    budget_head_id = Column(Integer, ForeignKey("budget_heads.id"))
    basic_amount = Column(Numeric(18, 2), nullable=False)
    tax_amount = Column(Numeric(18, 2), nullable=False)
    gross_amount = Column(Numeric(18, 2), nullable=False)
    ld_deduction = Column(Numeric(18, 2), default=0)
    retention_amount = Column(Numeric(18, 2), default=0)
    tds_it_amount = Column(Numeric(18, 2), default=0)
    tds_gst_amount = Column(Numeric(18, 2), default=0)
    other_deductions = Column(Numeric(18, 2), default=0)
    net_payable_amount = Column(Numeric(18, 2), nullable=False)
    match_status = Column(String(50), default='Pending')
    payment_status = Column(String(50), default='Initiated')
    utr_number = Column(String(100))
    payment_date = Column(Date)
    created_by = Column(BigInteger)
    created_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())

    work_order = relationship("MtrlWo")
    grn = relationship("MtrlGrn")
    party = relationship("MtrlParty")
    matching = relationship("MtrlMatch", back_populates="invoice", uselist=False, cascade="all, delete-orphan")

class MtrlMatch(Base):
    __tablename__ = "mtrl_match"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    invoice_id = Column(BigInteger, ForeignKey("mtrl_invoice.id", ondelete="CASCADE"), nullable=False)
    wo_id = Column(BigInteger, ForeignKey("mtrl_wo.id"), nullable=False)
    grn_id = Column(BigInteger, ForeignKey("mtrl_grn.id"), nullable=False)
    wo_total_amt = Column(Numeric(18, 2), nullable=False)
    grn_accepted_amt = Column(Numeric(18, 2), nullable=False)
    inv_claimed_amt = Column(Numeric(18, 2), nullable=False)
    rate_discrepancy = Column(Numeric(18, 2), default=0)
    qty_discrepancy = Column(Numeric(14, 2), default=0)
    tax_discrepancy = Column(Numeric(18, 2), default=0)
    match_verdict = Column(String(50), default='Full Match')
    passed_by = Column(BigInteger)
    created_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())

    invoice = relationship("MtrlInvoice", back_populates="matching")

class MtrlSecurity(Base):
    __tablename__ = "mtrl_security"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    sec_type = Column(String(50), nullable=False)
    tender_id = Column(BigInteger, ForeignKey("mtrl_tender.id"))
    wo_id = Column(BigInteger, ForeignKey("mtrl_wo.id"))
    party_id = Column(BigInteger, ForeignKey("mtrl_party.id"), nullable=False)
    instrument_type = Column(String(50), nullable=False)
    instrument_no = Column(String(100), nullable=False)
    instrument_date = Column(Date, nullable=False)
    expiry_date = Column(Date, nullable=False)
    claim_period_date = Column(Date)
    amount = Column(Numeric(18, 2), nullable=False)
    issuing_bank = Column(String(150))
    status_id = Column(BigInteger, ForeignKey("code_master.code_mst_id"))
    released_date = Column(Date)
    release_ref_no = Column(String(100))
    created_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())

    party = relationship("MtrlParty")
    tender = relationship("MtrlTender")

class MtrlWarranty(Base):
    __tablename__ = "mtrl_warranty"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    asset_serial_no = Column(String(100), nullable=False)
    item_id = Column(BigInteger, ForeignKey("mtrl_item.id"), nullable=False)
    variant_id = Column(BigInteger, ForeignKey("mtrl_variant.id"))
    grn_id = Column(BigInteger, ForeignKey("mtrl_grn.id"))
    wo_id = Column(BigInteger, ForeignKey("mtrl_wo.id"))
    party_id = Column(BigInteger, ForeignKey("mtrl_party.id"), nullable=False)
    custodian_store_id = Column(BigInteger, ForeignKey("mtrl_store.id"))
    warranty_start_date = Column(Date, nullable=False)
    warranty_end_date = Column(Date, nullable=False)
    warranty_terms = Column(Text)
    is_amc_active = Column(Boolean, default=False)
    amc_party_id = Column(BigInteger, ForeignKey("mtrl_party.id"))
    amc_end_date = Column(Date)
    status = Column(String(50), default='Under Warranty')

    item = relationship("MtrlItem")
    party = relationship("MtrlParty", foreign_keys=[party_id])

class MtrlDefect(Base):
    __tablename__ = "mtrl_defect"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    ticket_no = Column(String(60), nullable=False, unique=True)
    ticket_date = Column(Date, default=func.current_date())
    warranty_id = Column(BigInteger, ForeignKey("mtrl_warranty.id"))
    item_id = Column(BigInteger, ForeignKey("mtrl_item.id"), nullable=False)
    variant_id = Column(BigInteger, ForeignKey("mtrl_variant.id"))
    party_id = Column(BigInteger, ForeignKey("mtrl_party.id"), nullable=False)
    defect_category = Column(String(100), nullable=False)
    severity = Column(String(50), default='Medium')
    defect_desc = Column(Text, nullable=False)
    vendor_response = Column(Text)
    resolution_tat_due = Column(Date, nullable=False)
    resolved_date = Column(Date)
    resolution_status = Column(String(50), default='Reported')
    escalated_to_gem = Column(Boolean, default=False)
    logged_by = Column(BigInteger)
    created_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())

    item = relationship("MtrlItem")
    party = relationship("MtrlParty")

class MtrlDisposal(Base):
    __tablename__ = "mtrl_disposal"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    financial_year_id = Column(Integer, ForeignKey("financial_years.id"))
    disp_proposal_no = Column(String(60), nullable=False, unique=True)
    item_id = Column(BigInteger, ForeignKey("mtrl_item.id"), nullable=False)
    variant_id = Column(BigInteger, ForeignKey("mtrl_variant.id"))
    store_id = Column(BigInteger, ForeignKey("mtrl_store.id"), nullable=False)
    disposal_qty = Column(Numeric(14, 2), nullable=False)
    condemnation_reason = Column(String(100), nullable=False)
    book_value_amount = Column(Numeric(18, 2), nullable=False)
    reserve_price = Column(Numeric(18, 2), nullable=False)
    disposal_mode = Column(String(50), default='E-Auction')
    auction_ref_no = Column(String(100))
    realized_value = Column(Numeric(18, 2))
    buyer_name = Column(String(150))
    deposit_challan_no = Column(String(100))
    status_id = Column(BigInteger, ForeignKey("code_master.code_mst_id"))
    approved_by = Column(BigInteger)
    created_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())

    item = relationship("MtrlItem")
    store = relationship("MtrlStore")

class MtrlAudit(Base):
    __tablename__ = "mtrl_audit"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    financial_year_id = Column(Integer, ForeignKey("financial_years.id"), nullable=False)
    audit_no = Column(String(60), nullable=False, unique=True)
    audit_type = Column(String(50), default='Annual PV')
    store_id = Column(BigInteger, ForeignKey("mtrl_store.id"), nullable=False)
    period_label = Column(String(50))
    audit_team_lead = Column(String(150), nullable=False)
    start_date = Column(Date, nullable=False)
    end_date = Column(Date)
    audit_status = Column(String(50), default='In Progress')
    created_by = Column(BigInteger)
    created_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())

    store = relationship("MtrlStore")
    lines = relationship("MtrlAuditLn", back_populates="audit", cascade="all, delete-orphan")

class MtrlAuditLn(Base):
    __tablename__ = "mtrl_audit_ln"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    audit_id = Column(BigInteger, ForeignKey("mtrl_audit.id", ondelete="CASCADE"), nullable=False)
    item_id = Column(BigInteger, ForeignKey("mtrl_item.id"), nullable=False)
    variant_id = Column(BigInteger, ForeignKey("mtrl_variant.id"))
    book_qty = Column(Numeric(14, 2), nullable=False)
    physical_qty = Column(Numeric(14, 2), nullable=False)
    variance_value = Column(Numeric(18, 2), default=0)
    investigation_notes = Column(Text)
    adjustment_action = Column(String(50), default='Pending')

    audit = relationship("MtrlAudit", back_populates="lines")
    item = relationship("MtrlItem")

class MtrlAdjust(Base):
    __tablename__ = "mtrl_adjust"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    financial_year_id = Column(Integer, ForeignKey("financial_years.id"))
    adj_voucher_no = Column(String(60), nullable=False, unique=True)
    audit_id = Column(BigInteger, ForeignKey("mtrl_audit.id"))
    store_id = Column(BigInteger, ForeignKey("mtrl_store.id"), nullable=False)
    item_id = Column(BigInteger, ForeignKey("mtrl_item.id"), nullable=False)
    variant_id = Column(BigInteger, ForeignKey("mtrl_variant.id"))
    adjustment_type = Column(String(50), nullable=False)
    adj_qty = Column(Numeric(14, 2), nullable=False)
    adj_value = Column(Numeric(18, 2), nullable=False)
    approver_user_id = Column(BigInteger)
    sanction_order_no = Column(String(100), nullable=False)
    sanction_order_date = Column(Date, nullable=False)
    status_id = Column(BigInteger, ForeignKey("code_master.code_mst_id"))
    created_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())

    item = relationship("MtrlItem")
    store = relationship("MtrlStore")

class MtrlForecast(Base):
    __tablename__ = "mtrl_forecast"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    financial_year_id = Column(Integer, ForeignKey("financial_years.id"), nullable=False)
    item_id = Column(BigInteger, ForeignKey("mtrl_item.id"), nullable=False)
    variant_id = Column(BigInteger, ForeignKey("mtrl_variant.id"))
    store_id = Column(BigInteger, ForeignKey("mtrl_store.id"), nullable=False)
    annual_consumption = Column(Numeric(14, 2), nullable=False)
    current_stock_qty = Column(Numeric(14, 2), nullable=False)
    pending_receipt_qty = Column(Numeric(14, 2), default=0)
    projected_demand = Column(Numeric(14, 2), nullable=False)
    suggested_order_qty = Column(Numeric(14, 2), nullable=False)
    lead_time_buffer = Column(Numeric(14, 2), default=0)
    est_budget_required = Column(Numeric(18, 2), nullable=False)
    budget_head_id = Column(Integer, ForeignKey("budget_heads.id"))
    created_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())

    item = relationship("MtrlItem")
    store = relationship("MtrlStore")

class MtrlWfCfg(Base):
    __tablename__ = "mtrl_wf_cfg"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    module_name = Column(String(50), nullable=False)
    stage_sequence = Column(Integer, nullable=False)
    stage_name = Column(String(100), nullable=False)
    required_role = Column(String(100), nullable=False)
    min_amount = Column(Numeric(18, 2), default=0)
    max_amount = Column(Numeric(18, 2))
    sla_tat_hours = Column(Integer, default=48)
    escalation_role = Column(String(100))
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())

class MtrlLimit(Base):
    __tablename__ = "mtrl_limit"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    role_name = Column(String(100), nullable=False, unique=True)
    direct_purchase_lim = Column(Numeric(18, 2), nullable=False)
    quotation_proc_lim = Column(Numeric(18, 2), nullable=False)
    limited_tender_lim = Column(Numeric(18, 2), nullable=False)
    open_tender_lim = Column(Numeric(18, 2), nullable=False)
    disposal_writeoff = Column(Numeric(18, 2), nullable=False)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())

class MtrlNotif(Base):
    __tablename__ = "mtrl_notif"
    id = Column(BigInteger, primary_key=True, index=True)
    tenant_id = Column(BigInteger, ForeignKey("tenant_master.tenant_id"))
    branch_id = Column(BigInteger)
    entity_id = Column(BigInteger, ForeignKey("entity_master.entity_id"))
    department_id = Column(Integer, ForeignKey("departments.id"))
    office_id = Column(Integer, ForeignKey("offices.id"))
    user_id = Column(BigInteger)
    target_role = Column(String(100))
    event_type = Column(String(50), nullable=False)
    title = Column(String(255), nullable=False)
    message = Column(Text, nullable=False)
    action_route = Column(String(150))
    is_read = Column(Boolean, default=False)
    read_at = Column(DateTime(timezone=True))
    created_at = Column(DateTime(timezone=True), server_default=func.clock_timestamp())
